name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'

    - name: Install dependencies
      run: |
        npm install -g -y elm
        npm install -g -y elm-format
        npm install -g -y elm-test

    - name: Enforce formatting
      run: make fmt-check

    - name: Test
      run: make tests

    - name: Build
      run: make build
